parameters:
#    acme_first.example.class: Acme\FirstBundle\Example

services:
#    acme_first.example:
#        class: %acme_first.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
